### ISSUE TITLE
Allow running queries against templates

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#101]
From [ch885](https://app.clubhouse.io/interminedatabrowser/story/885/implement-design-system-with-css-variables)

Users have access to template queries, either publicly or with an api token. They should be able to update data visualization similarly to the general default tab.

Constraints:
- that are not "one of" should use input widgets
- have less than 10 items and are "one of" use a checkbox
### Tasks

- [x] move templates tab to the top of the app manager component
- [x] organize templates by category
- [x] display number of templates in each category
- [x] fix run query tooltip not closing on mouseout
- [x] show green tick when template is applied
- [x] show info button with description

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** Because we're only showing templates for the selected classview, the `Templates` tab no longer makes sense to have next to the class view tab. Instead it should be moved to the top of the constraints component.
