### ISSUE TITLE
Enforce codebase formatting

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#11]
From [ch397](https://app.clubhouse.io/interminedatabrowser/story/397/implement-design-system-with-css-variables)

Because we'll be setting `prettier` to use hard tabs for indentation, we'll need to use an `.editorConfig` file with similar settings so the code displays correctly on github.

---
### Approval Required

for preferred options:
https://prettier.io/docs/en/options.html
### Tasks

- [x] [set prettier to hard tabs](https://github.com/romejs/rome/issues/425)
- [x] add `.editorConfig` file
- [x] install [package.json plugin](https://github.com/shellscape/prettier-plugin-package)
- [x] [disable eslint conflicts](https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules)
