### ISSUE TITLE
Allow the user to enter an api key

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#116]
From [ch889](https://app.clubhouse.io/interminedatabrowser/story/889/implement-design-system-with-css-variables)

### Tasks

- [x] change text
- [x] change icon to a key icon
- [x] save api key in local storage
- [x] get key from local storage on mount
