### ISSUE TITLE
Scaffold branch with create-react-app

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#12]
From [ch386](https://app.clubhouse.io/interminedatabrowser/story/386/implement-design-system-with-css-variables)

I need access to the original implementation, and would like to keep the git history. So create a new branch and delete all files there. This is the simplest way to add `create-react-app` using `npx create-react-app .`
### Tasks

- [x] create branch and delete all files
- [x] migrate to using yarn v2
- [x] add `.DS_Store` file to `gitignore` if it doesn't exist
- [x] install create-react-app with `npx create-react-app .`
- [x] [add extra a11y eslint checks](https://reactjs.org/docs/accessibility.html#development-assistance)
