### ISSUE TITLE
Write up documentation for week 4 iteration

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#13]
From [ch573](https://app.clubhouse.io/interminedatabrowser/story/573/implement-design-system-with-css-variables)

Document color palette, typography, and `Text` component
### Tasks

- [x] install and configure storybook
- [x] Add mdx documentation on setting up the project
- [x] document palette
- [x] document typography components
- [x] Set script in package.json to launch storybook during development
