### ISSUE TITLE
Lists are not properly applied in the template query view

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#130]
From [ch929](https://app.clubhouse.io/interminedatabrowser/story/929/implement-design-system-with-css-variables)

When running queries with lists on templates, an error is thrown in the console panel. Lists seem to be properly applied for overview constraints, but this has to be vetted by an actual biologist that can determine if the results are indeed correct.
### Tasks

- [x] remove lists section from query controller
- [x] remove list tags from templates view
- [x] move the selected list to the top of the displayed values
- [x] show tag with selected name, truncated
