### ISSUE TITLE
Lift up the machine state by using xstate actors

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#138]
From [ch965](https://app.clubhouse.io/interminedatabrowser/story/965/implement-design-system-with-css-variables)

Some components need to fetch data before being mounted. In order to do this, we have to refactor to using xstate actors.
### Tasks

- [x] use an actor for the templates view tab
- [x] use an actor for the constraint input widgets
- [x] cache the app mine configuration
