### ISSUE TITLE
Show default value for template constraints

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#147]
From [ch942](https://app.clubhouse.io/interminedatabrowser/story/942/implement-design-system-with-css-variables)

Use a dropdown for single select constraints, suggest widgets for multiple, and input widgets for the rest of the constraints
### Tasks

- [x] show defaults for all constriants
- [x] use dropdown for single select constraints
- [x] use suggest for multi value inputs
- [x] use inputs for everything else
