### ISSUE TITLE
Build out the Button Component

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#18]
From [ch410](https://app.clubhouse.io/interminedatabrowser/story/410/implement-design-system-with-css-variables)

Scaffold the app's components without state, and ensure it stays responsive. 

Packages:
[reakit](https://reakit.io/)
### Tasks

- [x] show icons on left of button
- [x] make icons scalable
- [x] show icons on right of button
- [ ] make outline only buttons
- [ ] make an icon only button
- [ ] make icon only button circular
- [ ] enable focus only on tabs
