### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#188]
From [ch1015](https://app.clubhouse.io/interminedatabrowser/story/1015/implement-design-system-with-css-variables)

### Tasks

- [ ] Immer in App
- [ ] filterListsForClass in appManagerMachine
- [ ] remove storybook
- [ ] delete original app directory
