### ISSUE TITLE
build out constraints components

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#21]
From [ch604](https://app.clubhouse.io/interminedatabrowser/story/604/implement-design-system-with-css-variables)

Build out the components for each constraint. Since there is a finite list of constraint types, build out each accordingly rather than use an early abstraction.
### Tasks

- [x] Add aria-label to describe the purpose
- [x] Add count tab icon
- [x] Add label icon for one word labels
- [x] Add label icon for multiple word labels
- [x] remove unused icons from bundle
- [x] write documentation

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** Since we've switched to using `Blueprintjs` as our UI library, we now need to manually tree shake the icons package.
