### ISSUE TITLE
Layout the application

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#23]
From [ch605](https://app.clubhouse.io/interminedatabrowser/story/605/implement-design-system-with-css-variables)

This was originally a task in story #410.
### Tasks

- [x] Build out the navigation component
- [x] Add the Constraint history section
- [x] Layout the list of constraints
- [x] place an empty card for the chart
- [x] place and empty card for the table
- [x] change blueprintjs colors to match theme
- [x] change to blueprintjs text styles
