### ISSUE TITLE
Display results in the im-table component

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#25]
From [ch433](https://app.clubhouse.io/interminedatabrowser/story/433/implement-design-system-with-css-variables)

For now, use the `im-table` library to ensure that the presentation logic is correct. Later on in the process I'll redesign a table layout and sync the table with the constraint components
### Tasks

- [x] display results in table
- [x] add icon to cells
- [x] make cells links to its url
- [x] style table to take full width of container
- [x] change font size for cells
- [x] change font size for headers
- [x] style cells to have more white space
- [x] speed up scrolling
- [x] add button for save to list
- [x] add code snippet button
- [x] add export button

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** After going through the `im-tables` codebase, I realized that it was not necessary. I could use `imjs` directly since it has a `tableRows` method that returns a 2D matrix I can use to build the tables.

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** Removed `@blueprintjs/table`. Styling it proved to be difficult since it's tailored towards spreadsheet usage, and uses `position:absolute` on the style attribute.

Instead, manually iterating the 2D matrix array proved to be simpler. And now it's mobile responsive to tablet sizes.
