### ISSUE TITLE
Display results in chart component

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#27]
From [ch434](https://app.clubhouse.io/interminedatabrowser/story/434/implement-design-system-with-css-variables)

Display the gene length summaries in a pie and bar chart.

### Tasks

- [x] Render the pie chart
- [x] Render the bar chart
- [x] Make the pie chart responsive
- [x] Make the bar chart responsive

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** Settled on `react-chartjs-2` after struggling to style the svg labels using `nivo` and `victory` charts.

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** After @amand1996 comment about using `recharts`, I decided on it. The api is nicer and it's mobile responsive out of the box by adding a single component.
