### ISSUE TITLE
Maintain and display constraints history component

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#46]
From [ch364](https://app.clubhouse.io/interminedatabrowser/story/364/implement-design-system-with-css-variables)

### Tasks

- [x] Connect history component to state atoms
- [x] [only send events to registered machines](https://github.com/davidkpiano/xstate/issues/111)
- [x] Display current constraints
- [x] Display historical constraints
- [x] update constraint count, and prevent it from going over 26 total
- [x] add tests
