### ISSUE TITLE
Build the UI for a constraint with a checkbox pop up

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#48]
From [ch707](https://app.clubhouse.io/interminedatabrowser/story/707/implement-design-system-with-css-variables)

Create a reusable component that will enclose all constraints with a pop up, who's child components is provided by the parent. The checkbox must meet the following tasks:
### Tasks

- [x] display a non-ideal state when no items are found to display
- [x] disable all buttons when there are no constraints applied
- [x] disable the `Constraint Set` tag, and enable the `Add Constraint` button when selections change
- [x] enable the `Reset Constraint` button and `Constraint Set` tag when the constraint has been applied
