### ISSUE TITLE
Build the UI for a suggest box constraint

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#50]
From [ch708](https://app.clubhouse.io/interminedatabrowser/story/708/implement-design-system-with-css-variables)

### Tasks

- [x] display non ideal state
- [x] display selected items
- [x] remove item from available selections if already selected
- [x] display if constraints have been updated
- [x] display if constraints have been applied
- [x] remove constraints from selection
- [x] conduct a weighted search over constraints
- [x] inform the user when there are no matches
- [x] focus the input after selecting a constraint
