### ISSUE TITLE
Configure jest testing

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#7]
From [ch401](https://app.clubhouse.io/interminedatabrowser/story/401/implement-design-system-with-css-variables)

Stub out simple unit and implementation tests to ensure the testing framework is properly configured.
### Tasks

- [x] write out unit tests for non UI code
- [x] write out implementation tests using [react-testing-library](https://testing-library.com/docs/react-testing-library/intro)
- [x] [add jest-axe for a11y testing](https://github.com/nickcolley/jest-axe#testing-react-with-react-testing-library)
