### ISSUE TITLE
Load the default queries when loading the app

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#70]
From [ch753](https://app.clubhouse.io/interminedatabrowser/story/753/implement-design-system-with-css-variables)

When first loading the application, the default query for all the components should be displayed
### Tasks

- [x] retrieve constraint values from imjs
- [x] retrieve pie chart values from imjs
- [x] retrieve gene length from imjs
- [x] retrieve table rows from imjs
