### ISSUE TITLE
Selects with large datasets should not lag

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#76]
From [ch784](https://app.clubhouse.io/interminedatabrowser/story/784/implement-design-system-with-css-variables)

Currently large datasets for dropdown selects cause the popup view to lag. Rendering the items in a virtualized list should alleviate this.
### Tasks

- [x] clicking on an item should not close the popup
- [x] focus first item in the list
- [x] use react-window to virtualize the list
- [x] scroll the item into view if a user scrolls past is with the keyboard
- [x] set `initialContent` and `noResults` manually

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** Fuzzy searching the large list is causing too much of a bottleneck. So this is blocked until that's resolved.
