### ISSUE TITLE
Configure linaria css-in-js

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#8]
From [ch389](https://app.clubhouse.io/interminedatabrowser/story/389/implement-design-system-with-css-variables)

We will use `linaria` to implement styling. This requires a custom webpack plugin, so we have to install it using craco to avoid that.
### Tasks

- [x] [intall craco with these instructions](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#installation)
- [x] [install linaria craco plugin and configure](https://www.npmjs.com/package/craco-linaria)
- [x] add `src/.linaria_cache` to `.gitignore` file
- [x] [configure style linting](https://github.com/callstack/linaria/blob/master/docs/LINTING.md)
- [x] [set `displayName: true` in config only when in development](https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options)
- [x] [add `linaria/babel` preset to babel config](https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#linariababel-preset)
- [x] normalize css with [modern-normalize](https://github.com/sindresorhus/modern-normalize)
- [x] minify css with webpack in production
- [x] migrate css files to linaria
- [x] move linaria babel options to config
