### ISSUE TITLE
Perform a query against the selected class view

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#83]
From [ch818](https://app.clubhouse.io/interminedatabrowser/story/818/implement-design-system-with-css-variables)

When the class view is updated, the query should be run against it. Yet, changing the class view should reset all the constraints.
### Tasks

- [x] fetch and display class models from the selected mine
- [x] reset the applied constraints when the class changes
- [x] update the query controller with the new class to set for the query
- [x] make lists filterable
