### ISSUE TITLE
Improve loading times

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#85]
From [ch828](https://app.clubhouse.io/interminedatabrowser/story/828/implement-design-system-with-css-variables)

The app currently makes multiple duplicated api calls, and this causes visual stutter with larger datasets
### Tasks

- [x] remove duplicate api calls
- [x] create search indexes when the user hovers over the element
- [x] create search index only after constraint loads

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** When reviewing resetting constraints, might be good to look at the `queryControllerMachine`'s `removeConstraint` action. It creates a new array each time its called by filtering the constraints. The filtering isn't the problem though. Instead the issue is that `filter` creates a new array each time. Therefore the `QueryController` will always re-render.

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** I could not reproduce the issue mentioned in the comment above, so deleted the task
