### ISSUE TITLE
Add skeletons when loading content

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#87]
From [ch409](https://app.clubhouse.io/interminedatabrowser/story/409/implement-design-system-with-css-variables)

Skeleton loaders improve the perceived load time. `Blueprintjs` has a classname for loading skeletons. Apply it while indexing search results or actually waiting on network calls.
### Tasks

- [x] pie chart loader
- [x] bar chart loader
- [x] table chart loader
- [x] fix UI loaders hanging

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** `recharts` does not provide a means to add classes to the rendered items, so we can't use the `blueprintjs` skeleton classes. Instead use a loading spinner or progress bar.
