### ISSUE TITLE
Fix class view input not filtering on user input

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#89]
From [ch849](https://app.clubhouse.io/interminedatabrowser/story/849/implement-design-system-with-css-variables)

### Tasks

- [x] filter classes on search query
- [x] change available classes when the mine changes
- [x] recreate the index for the new classes

**Comment by JM-Mendez** [comment]
manually merged in #90
