### ISSUE TITLE
Handle errors from api calls in the machines

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#91]
From [ch783](https://app.clubhouse.io/interminedatabrowser/story/783/implement-design-system-with-css-variables)

`imjs.service` has an `errorHandler` option to allow us to handle errors from the library
### Tasks

- [x] disable constraints that are not available for a mine
- [x] disable constraints that are not available for a class
- [x] handle errors from constraints not being available
- [x] show error state for bar chart
- [x] show error state for pie chart
- [x] show error state for table chart
