### ISSUE TITLE
Paginate the table rows

### ISSUE THREAD

**Issue by JM-Mendez** [JM-Mendez/InterMine-Data-Browser-Tool#99]
From [ch864](https://app.clubhouse.io/interminedatabrowser/story/864/implement-design-system-with-css-variables)

Table rows should be able to be paginated, with a cache limit set by the user.
### Tasks

- [x] cache received pages
- [x] enable paging forward
- [x] enable paging backwards
- [x] enable skipping to first page
- [x] enable skipping to last page
- [x] make page number input width large enough for multiple number
- [x] reset page number when updating query

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** Only fetching the 1st, 5th and 10th page may not be useful, since the network calls may take long. So the reason for caching is to avoid long loading times when navigating between pages

**Comment by JM-Mendez** [comment]
**[Comment from Clubhouse user @john_mendez:]** Look into what `im-tables` does and see if you can replicate, or at least emulate their algo.
